# -*- coding: utf-8 -*-
"""data_preprocessing1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBT-NKJT85hOtGaEMSxETeoHDW2NPevj
"""

import pandas as pd
print("pandas loaded")

df = pd.read_excel("flipkart_sales_data.xlsx")
df.drop(columns=['Order ID', 'Order Date'], inplace=True)
df

df.isna().sum()

df.columns[df.isna().any()].tolist()

cat_columns = df.select_dtypes(include='object').columns.tolist()
cat_columns

for col in cat_columns:
  mode = df[col].mode()[0]
  df[col] = df[col].fillna(mode)

df.isna().sum()

# num_columns = df.select_dtypes(exclude='object').columns.tolist()
# num_columns
num_columns = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
num_columns
df[num_columns].describe()



for col in num_columns:
  mean_value = df[col].mean()
  df[col] = df[col].fillna(mean_value)

df.isna().sum()

outlier_info = {}

for col in num_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_info[col] = outliers.shape[0]

    print(f"{col}: {outliers.shape[0]} outliers")

df[(df['Sales Amount'] < lower_bound) | (df['Sales Amount'] > upper_bound)]
#df[(df['cat_col_1'] < lower_bound) | (df['cat_col_1'] > upper_bound)] in general form

df.dtypes

# df['Order Date'] = pd.to_datetime(df['Order Date'])

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

#encodin - one hot encoding
df_one__hot_encoding = pd.get_dummies(df, columns=cat_columns)
df_one__hot_encoding = df_one__hot_encoding.astype(int)
df_one__hot_encoding

#feature scaling
import numpy as np
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_one__hot_encoding[num_columns] = scaler.fit_transform(df_one__hot_encoding[num_columns])
df_one__hot_encoding.head()